force-app/main/default/objects/Data_Anonymisation__mdt/Data_Anonymisation__mdt.object-meta.xml
<CustomObject>
    <label>Data Anonymisation</label>
    <pluralLabel>Data Anonymisations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Compound_Field__c.field-meta.xml
<CustomField>
    <fullName>Compound_Field__c</fullName>
    <label>Compound Field</label>
    <metadataRelationshipControllingField>Data_Anonymisation__mdt.SObject__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Data_Anonymisations</relationshipLabel>
    <relationshipName>Data_Anonymisations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Mix</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <metadataRelationshipControllingField>Data_Anonymisation__mdt.SObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Data_Anonymisations</relationshipLabel>
    <relationshipName>Data_Anonymisations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Length_of_Data__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Data__c</fullName>
    <label>Length of Data</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Data_Anonymisations</relationshipLabel>
    <relationshipName>Data_Anonymisations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/ContactAnonymiser.cls
/**
 * @description  : Helper class to anonymise passed in Contact
 * @author       : simon@hyphen8.com
 * @created      : 19/10/2021
**/
public without sharing class ContactAnonymiser {
    private List<Data_Anonymisation__mdt> metaDataToUse;
    private Contact contactToUpdate;
    private Set<String> fieldsToUpdate;
    private SObjectIndex metaByObject;
    private SObjectIndex metaByFieldName;
    private SObjectIndex metaByCompoundField;

    public ContactAnonymiser(Contact contact, List<Data_Anonymisation__mdt> metaData) {
        this.contactToUpdate = contact;
        this.metaDataToUse = metaData;
        this.metaByObject = new SObjectIndex('SObject__r.QualifiedApiName')
            .putAll(this.metaDataToUse);

        List<Data_Anonymisation__mdt> allMeta = (List<Data_Anonymisation__mdt>)metaByObject.getAll('Contact');

        this.metaByFieldName = new SObjectIndex('Field_Name__r.QualifiedApiName')
            .putAll(allMeta);
        this.metaByCompoundField = new SObjectIndex('Compound_Field__r.QualifiedApiName')
            .putAll(allMeta);
    }

    public ContactAnonymiser setFields(Set<String> fields){
        this.fieldsToUpdate = fields;
        return this;
    }

    public Contact anonymise(){
        for (String fieldToUpdate : this.fieldsToUpdate){
            if (!'Email'.equalsIgnoreCase(fieldToUpdate)){
                Data_Anonymisation__mdt metaRecord = (Data_Anonymisation__mdt)metaByCompoundField.get(fieldToUpdate);
                if (null == metaRecord){
                    metaRecord = (Data_Anonymisation__mdt)metaByFieldName.get(fieldToUpdate);
                }
                this.contactToUpdate.put(fieldToUpdate, AnonymiseHelper.generateRandomString(metaRecord.Data_Type__c, Integer.valueOf(metaRecord.Length_of_Data__c)));    
            }else {
                List<Data_Anonymisation__mdt> emailMetaData = metaByFieldName.getAll('Email');
                Map<String, String> emailMap = new Map<String, String>();
                for (Data_Anonymisation__mdt emailData : emailMetaData){
                    if ('Contact Email'.equalsIgnoreCase(emailData.MasterLabel)){
                        emailMap.put('Address', AnonymiseHelper.generateRandomString(emailData.Data_Type__c, Integer.valueOf(emailData.Length_of_Data__c)));
                    }else if ('Contact EMail Domain'.equalsIgnoreCase(emailData.MasterLabel)){
                        emailMap.put('Domain', AnonymiseHelper.generateRandomString(emailData.Data_Type__c, Integer.valueOf(emailData.Length_of_Data__c)));
                    }
                }
                String[] emailSplit = this.contactToUpdate.Email.split('@');
                emailSplit[0] = emailMap.get('Address');
                emailSplit[1] = emailMap.get('Domain');
                this.contactToUpdate.Email = String.join(emailSplit, '@');
            }
            
        }

        return this.contactToUpdate;
    }
}