force-app/main/default/objects/Data_Anonymisation__mdt/Data_Anonymisation__mdt.object-meta.xml
<CustomObject>
    <label>Data Anonymisation</label>
    <pluralLabel>Data Anonymisations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Mix</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <metadataRelationshipControllingField>Data_Anonymisation__mdt.SObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Data_Anonymisations</relationshipLabel>
    <relationshipName>Data_Anonymisations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Length_of_Data__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Data__c</fullName>
    <label>Length of Data</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Data_Anonymisations</relationshipLabel>
    <relationshipName>Data_Anonymisations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/BatchAnonymiseContactsTest.cls
/**
 * @description  : 
 * @author       : simon@hyphen8.com
 * @created      : 19/10/2021
**/
@IsTest
public class BatchAnonymiseContactsTest {
    @IsTest
    static void testContactAnonymise(){
        //Set up test data
        List<Contact> contactsBeforeAnonymise = new List<Contact>();

        Account account = new Account(Name='Test Account');
        insert account;

        for (Integer i = 0 ; i < 100 ; i++){
            contactsBeforeAnonymise.add(new Contact(
                FirstName = 'Test_' + i,
                LastName = 'Contact_' + i,
                Email = 'test_' + i + '.contact_' + i + '@myemail.com',
                MobilePhone = '0123456789' + (i < 10 ? '0' + i : ''+i),
                AccountId = account.Id
            ));
        }

        insert contactsBeforeAnonymise;

        List<Data_Anonymisation__mdt> mockMetaData = new MockMetaManager('Data_Anonymisation__mdt')
            .addFieldValue('MasterLabel', 'Contact Email')
            .addFieldValue('DeveloperName', 'Contact_Email')
            .addFieldValue('Data_Type__c','String')
            .addFieldValue('Length_of_Data__c',10)
            .addEntityDefinition('SObject__c','Contact')
            .addFieldDefinition('Field_Name__c','Email')
            .getMockMetaData();


        List<Data_Anonymisation__mdt> allMetaData = new List<Data_Anonymisation__mdt>();
        allMetaData.addAll(mockMetaData);

        test.startTest();
            BatchAnonymiseContacts.mockMetaData = allMetaData;

            ID batchId = Database.executeBatch(new BatchAnonymiseContacts(), 200);

        test.stopTest();

        //TODO:
        //Create custom metadata so that we DON'T have to rely on it being in the org using MockMetaManager class
        //Set the mock metadata into the actual class
        //Run the test
        //Assert our tests

    }
}