force-app/main/default/objects/Data_Anonymisation__mdt/Data_Anonymisation__mdt.object-meta.xml
<CustomObject>
    <label>Data Anonymisation</label>
    <pluralLabel>Data Anonymisations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Compound_Field__c.field-meta.xml
<CustomField>
    <fullName>Compound_Field__c</fullName>
    <label>Compound Field</label>
    <metadataRelationshipControllingField>Data_Anonymisation__mdt.SObject__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Data_Anonymisations</relationshipLabel>
    <relationshipName>Data_Anonymisations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Mix</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <metadataRelationshipControllingField>Data_Anonymisation__mdt.SObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Data_Anonymisations</relationshipLabel>
    <relationshipName>Data_Anonymisations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/Length_of_Data__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Data__c</fullName>
    <label>Length of Data</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Data_Anonymisation__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Data_Anonymisations</relationshipLabel>
    <relationshipName>Data_Anonymisations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/ContactAnonymiserTest.cls
/**
 * @author       : simon@hyphen8.com
 * @created      : 19/10/2021
**/
@IsTest
public class ContactAnonymiserTest {
    @IsTest
    static void testContactAnonymiserSingle(){
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'test.contact@myemail.com',
            MobilePhone = '07999999999'
        );

        List<Data_Anonymisation__mdt> allMetaData = new List<Data_Anonymisation__mdt>();
        Set<String> fieldsToTest = new Set<String>{
            'FirstName',
            'LastName',
            'Email',
            'MobilePhone'
        };

        for (String fieldToTest : fieldsToTest){
            if ('FirstName'.equalsIgnoreCase(fieldToTest) || 'LastName'.equalsIgnoreCase(fieldToTest)){
                List<Data_Anonymisation__mdt> fieldMeta = new MockMetaManager('Data_Anonymisation__mdt')
                    .addFieldValue('MasterLabel', 'Contact ' + fieldToTest)
                    .addFieldValue('DeveloperName', 'Contact_'+fieldToTest)
                    .addFieldValue('Data_Type__c','String')
                    .addFieldValue('Length_of_Data__c',8)
                    .addEntityDefinition('SObject__c','Contact')
                    .addFieldDefinition('Compound_Field__c',fieldToTest)
                    .getMockMetaData();

                allMetaData.addAll(fieldMeta);
            }else if ('Email'.equalsIgnoreCase(fieldToTest)){
                List<Data_Anonymisation__mdt> fieldMeta = new MockMetaManager('Data_Anonymisation__mdt')
                    .addFieldValue('MasterLabel', 'Contact ' + fieldToTest)
                    .addFieldValue('DeveloperName', 'Contact_'+fieldToTest)
                    .addFieldValue('Data_Type__c','Mix')
                    .addFieldValue('Length_of_Data__c',8)
                    .addEntityDefinition('SObject__c','Contact')
                    .addFieldDefinition('Field_Name__c',fieldToTest)
                    .getMockMetaData();

                List<Data_Anonymisation__mdt> fieldMetaDomain = new MockMetaManager('Data_Anonymisation__mdt')
                    .addFieldValue('MasterLabel', 'Contact ' + fieldToTest + ' Domain')
                    .addFieldValue('DeveloperName', 'Contact_'+fieldToTest + '_Domain')
                    .addFieldValue('Data_Type__c','Mix')
                    .addFieldValue('Length_of_Data__c',8)
                    .addEntityDefinition('SObject__c','Contact')
                    .addFieldDefinition('Field_Name__c',fieldToTest)
                    .getMockMetaData();

                allMetaData.addAll(fieldMeta);
                allMetaData.addAll(fieldMetaDomain);

            }else if ('MobilePhone'.equalsIgnoreCase(fieldToTest)){
                List<Data_Anonymisation__mdt> fieldMeta = new MockMetaManager('Data_Anonymisation__mdt')
                    .addFieldValue('MasterLabel', 'Contact ' + fieldToTest)
                    .addFieldValue('DeveloperName', 'Contact_'+fieldToTest)
                    .addFieldValue('Data_Type__c','Number')
                    .addFieldValue('Length_of_Data__c',11)
                    .addEntityDefinition('SObject__c','Contact')
                    .addFieldDefinition('Field_Name__c',fieldToTest)
                    .getMockMetaData();

                allMetaData.addAll(fieldMeta);
            }
        }

        Test.startTest();

        System.assertEquals(testContact.FirstName, 'Test');
        System.assertEquals(testContact.LastName, 'Contact');
        System.assertEquals(testContact.Email, 'test.contact@myemail.com');
        System.assertEquals(testContact.MobilePhone, '07999999999');
        
        testContact = new ContactAnonymiser(testContact, allMetaData)
            .setFields(fieldsToTest)
            .anonymise();
        
        Test.stopTest();

        System.assertNotEquals(testContact.FirstName, 'Test');
        System.assertNotEquals(testContact.LastName, 'Contact');
        System.assertNotEquals(testContact.Email, 'test.contact@myemail.com');
        System.assertNotEquals(testContact.MobilePhone, '07999999999');
    }
}