force-app/main/default/objects/Account/fields/Send_Latest_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Latest_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Latest Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email_Log__c/Email_Log__c.object-meta.xml
<CustomObject>
    <description>Stores Email Logs</description>
    <label>Email Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Email Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Email Logs</relationshipLabel>
    <relationshipName>Email_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_Log__c/fields/Last_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Last_Email_Sent__c</fullName>
    <label>Last Email Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AccountSendEmailHandlerTest.cls
/**
 * @author       : simon@hyphen8.com
 * @created      : 22/09/2021
**/
@IsTest
public class AccountSendEmailHandlerTest {
    @IsTest
    static void testAccountUpdateWithLogs(){
        Account account = new Account(
            Name = 'Test Account'
        );
        insert account;

        List<Contact> contacts = new List<Contact>();
        List<Email_Log__c> emailLogs = new List<Email_Log__c>();

        for (Integer i = 0 ; i < 5 ; i++){
            contacts.add(new Contact(
                FirstName = 'Test',
                LastName = 'Contact' + i,
                Email = 'test.contact' + i + '@myemail.com',
                AccountId = account.Id
            ));
            emailLogs.add(new Email_Log__c(
                First_Name__c = 'Test',
                Last_Name__c = 'Contact' + i,
                Email__c = 'test.contact' + i + '@myemail.com',
                Account__c = account.Id
            ));
        }
        //Now create records with same Email address
        for (Integer i = 0 ; i < 5 ; i++){
            contacts.add(new Contact(
                FirstName = 'Test',
                LastName = 'OtherContact' + i,
                Email = 'test.contact' + i + '@myemail.com',
                AccountId = account.Id
            ));
            emailLogs.add(new Email_Log__c(
                First_Name__c = 'Test',
                Last_Name__c = 'OtherContact' + i,
                Email__c = 'test.contact' + i + '@myemail.com',
                Account__c = account.Id
            ));
        }

        insert contacts;
        insert emailLogs;

        Test.startTest();
        AccountSendEmailHandler handler = new AccountSendEmailHandler();
        handler.handleAfterUpdate(new List<Account>{account}, new List<Account>{
            new Account(
                Id = account.Id,
                Send_Latest_Email__c = true
            )
        });
        Test.stopTest();

        emailLogs = [
            SELECT Id, Last_Email_Sent__c
            FROM Email_Log__c
            WHERE Account__c = :account.Id
        ];

        for (Email_Log__c emailLog : emailLogs){
            System.assertEquals(Date.today(), emailLog.Last_Email_Sent__c.date(), 'Correct date sent');
        }
    }
}